title: Just the Docs Template - Neel Kanani
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://neelkanani.github.io/neelkanani1227

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout
